name: molecule
services:
  - name: molecule-web
    environment_slug: php
    github:
      branch: main
      deploy_on_push: true
      repo: nikbr/molecule
    environment_variables:
      - key: APP_ENV
        scope: RUN_AND_BUILD_TIME
        value: prod
      - key: APP_SECRET
        scope: RUN_TIME
        value: ${molecule-web.APP_SECRET}
      - key: DOCUMENT_ROOT
        scope: RUN_AND_BUILD_TIME
        value: public
      - key: BP_PHP_WEB_DIR
        scope: RUN_AND_BUILD_TIME
        value: public
    run_command: heroku-php-apache2 public
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
